version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - climatepolicyradar/deng
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - climatepolicyradar/deng
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
